Resolve unused variable 'vtxItr' compiler error
Clang 3.5.0 complains:

    Calibration/IsolatedParticles/plugins/IsolatedTracksHcalScale.cc:151:43:
    error: unused variable 'vtxItr' [-Werror,-Wunused-variable]

The patch removes `vtxItr`.

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>